version: '3.8'

services:
  backend:
    build: ./backend
    container_name: educonnect-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend/instance:/app/instance
    environment:
      FLASK_ENV: development